name: "material_drawer_items"
description: "Material drawer items for Angular2."
version: "0.0.1"
homepage: "https://github.com/olimou/dart_material_list"
author: "Emerson Moura <oilmou@gmail.com>"

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: "^2.2.0"
  angular2_components: ">=0.2.1 <1.0.0"

dev_dependencies:
  test: ^0.12.0

transformers:
  - angular2:
      entry_points: "web/main.dart"
      platform_directives:
        - "package:angular2/common.dart#COMMON_DIRECTIVES"
      platform_pipes:
        - "package:angular2/common.dart#COMMON_PIPES"